### ISSUE TITLE
Great Project ! One question

### ISSUE THREAD

**Issue by Bubu31** [gibbed/Gibbed.RED4#4]
Hello, first of all great project! 
My question is about the mini-map patch, I understand the principle of what you did however I can't understand how you knew you could change the zoom with the visionRadiusVehicle value, I tried to use the dump project to find a trace of it but it was impossible to find.

**Comment by gibbed** [comment]
A bit of clever reverse engineering. 😄 

What originally transpired is someone noted those names existed as strings in the game's executable. I found that interesting so I began to look at how those strings were being used.

I discovered that they were properties being defined in the game's RTTI object system for a class named `MinimapContainerController`. Since they were being defined this way I experimented to see if I could add them to the script cache as new property definitions since the class they were defined on was already defined, and it worked!

Just these particular properties were never defined/accessed in the game's original scripts which is why they're not already defined.
